### ISSUE TITLE
CircUp attempts to update Mac Ghost files starting with ._ during update

### ISSUE THREAD

**Issue by makermelissa** [ntoll/circup#10]
These are files caused by copying on the CircuitPython drive from a Mac. They can be seen with `ls -Ra /Volumes/CIRCUITPY/lib/` and should probably be ignored.

**Comment by ntoll** [comment]
Good catch. I develop on Linux, but tested on Mac and missed this in my haste.

This should be relatively easy to fix by discarding all files whose names a pre-pended with a dot (i.e they follow the unix "hidden dot file" convention, described here: https://linux-audit.com/linux-history-how-dot-files-became-hidden-files/).

**Comment by ntoll** [comment]
@makermelissa adb4cf7 should do the trick. :+1: Thanks for the suggestion / report.
